on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  print-git-config:
    name: "Print git config"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: "Print git config"
        run: |
          git config --list
          git remote -v
          git branch -v
          git tag -l
        shell: bash
